baseURL: ""
languageCode: "en-us"
title: "HW Travelog"
hasCJKLanguage: true
params: 
  heading: ""
frontmatter: 
  date: 
    - :filename
    - :default
permalinks: 
blackfriday: 
  fractions: false
  extensionsmask: 
    - noIntraEmphasis
markup: 
  # https://gohugo.io/getting-started/configuration-markup#goldmark
  # https://github.com/yuin/goldmark/
  goldmark: 
    extensions: 
      typographer: true
    renderer: 
      unsafe: true # render raw HTML
      hardWraps: true # render newlines as <br>